/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import modelo.Cliente;
import Controladores.ControladorPrincipal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import modelo.PersistenciaGeneral;



/**
 *
 * @author blanc
 */
public class GestionClientes extends javax.swing.JPanel {
    private ControladorPrincipal controlador;
    private ArrayList<Cliente> listaClientes;
    /**
     * Creates new form GestionClientes
     */
    public GestionClientes(ControladorPrincipal controlador) {
        initComponents();
        this.controlador = controlador;
        this.listaClientes = PersistenciaGeneral.cargarListaClientes("listaClientes.dat");
        
        actualizarTablaClientes();
    }
    
     private void actualizarTablaClientes() {
        DefaultTableModel modeloTabla = (DefaultTableModel) jTableClientes.getModel();
        modeloTabla.setRowCount(0); // Limpiar la tabla antes de agregar nuevas filas

        for (Cliente cliente : listaClientes) {
            modeloTabla.addRow(new Object[]{cliente.getNombre(),cliente.getNumeroTel(),cliente.getPreferencia()});
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        agregarclt_btn = new javax.swing.JButton();
        borrarclt_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nombreC = new javax.swing.JTextField();
        telefonoC = new javax.swing.JTextField();
        preferenciaC = new javax.swing.JTextField();

        setBackground(new java.awt.Color(192, 232, 192));

        jLabel1.setText("Nombre del Cliente:");

        jLabel2.setText("Número Teléfonico:");

        jLabel3.setText("Preferencia:");

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del Cliente", "Número Teléfonico", "Correo Electrónico"
            }
        ));
        jScrollPane1.setViewportView(jTableClientes);

        agregarclt_btn.setText("Agregar");
        agregarclt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarclt_btnActionPerformed(evt);
            }
        });

        borrarclt_btn.setText("Eliminar");
        borrarclt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarclt_btnActionPerformed(evt);
            }
        });

        jLabel5.setText("Gestión de Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(agregarclt_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrarclt_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(telefonoC, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(preferenciaC, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(21, 21, 21)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel4)
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(telefonoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(preferenciaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarclt_btn)
                            .addComponent(borrarclt_btn))
                        .addContainerGap(202, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarclt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarclt_btnActionPerformed
        try {
            if(nombreC.getText().equals("")|| telefonoC.getText().equals("")|| preferenciaC.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Please Enter all data");
            }else{
               Cliente cliente = new Cliente(nombreC.getText(), telefonoC.getText(), preferenciaC.getText());
               listaClientes.add(cliente);
                // Mostrar un mensaje de éxito
               JOptionPane.showMessageDialog(this, "Add data successfully");
               
               // Limpiar los campos de entrada
               nombreC.setText("");
               telefonoC.setText("");
               preferenciaC.setText("");
               
               PersistenciaGeneral.guardarListaClientes(listaClientes, "listaClientes.dat");
               DefaultTableModel tblModel = (DefaultTableModel) jTableClientes.getModel();
                tblModel.addRow(new Object[]{cliente.getNombre(), cliente.getNumeroTel(),cliente.getPreferencia()});
               }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println(ex.getMessage());
        }
                        
    }//GEN-LAST:event_agregarclt_btnActionPerformed

    private void borrarclt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarclt_btnActionPerformed
      
    }//GEN-LAST:event_borrarclt_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarclt_btn;
    private javax.swing.JButton borrarclt_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField nombreC;
    private javax.swing.JTextField preferenciaC;
    private javax.swing.JTextField telefonoC;
    // End of variables declaration//GEN-END:variables
}
